import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app.sendsay.ru/');
  await page.goto('https://app.sendsay.ru/dashboard');
  await page.goto('https://app.sendsay.ru/signin');
  await page.getByTestId('login').click();
  await page.getByTestId('login').fill('codeception');
  await page.getByTestId('login').press('Tab');
  await page.getByTestId('password').fill('eepe5See');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByText('What\'s new?Getting startedTask journalcodeceptioncodeception').click();
  await page.getByText('codeception').nth(1).click();
  await page.getByRole('link', { name: 'Account settings' }).click();
  await page.getByText('Русский').click();
  await page.locator('.RootSideNavigation-mainLinks > a:nth-child(3)').click();
  await page.getByTestId('SectionHeader-button').click();
  await page.getByRole('button', { name: 'Email' }).click();
  await page.getByRole('button', { name: 'Выбрать аудиторию' }).click();
  await page.getByText('Подписчики, получившие много писем').click();
  await page.getByText('Список контактов').click();
  await page.getByText('В список будут добавлены все получатели рассылки').click();
  await page.getByText('Включить тематическую отписку').click();
  await page.getByRole('button', { name: 'Выберите список' }).nth(3).click();
  await page.getByRole('button', { name: 'Email Список для импорта pl65621' }).click();
  await page.getByRole('button', { name: 'Сохранить' }).click();
  await page.getByTestId('recipientsStep').getByRole('list').getByRole('button', { name: 'Выберите список' }).click();
  await page.getByRole('button', { name: 'Email Список для импорта pl65621' }).click();
  await page.getByTestId('recipientsStep').getByRole('list').getByRole('button', { name: 'Список для импорта' }).click();
  await page.getByRole('button', { name: 'Email [AV] asket.space pl31609' }).click();
  await page.getByRole('button', { name: 'Сохранить' }).click();
  await page.getByText('Список контактов').click();
  await page.getByText('Список контактов').click();
});
