name: Check PR
on: [pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest

    env:
      FORCE_COLOR: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Eslint
        run: yarn eslint

      - name: Prettier
        run: yarn pretify

  tests:
    runs-on: ubuntu-latest
    env:
      DEPLOY_NAME: sendsay-docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: URL
        id: url
        shell: bash
        run: echo "link=https://deploy-preview-${{ github.event.pull_request.number }}--${{ env.DEPLOY_NAME }}.netlify.app" >> $GITHUB_OUTPUT

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ steps.url.outputs.link }}
        run: yarn e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report
            playwright-artifacts
          retention-days: 30

  autofix:
    needs: [checks]
    runs-on: ubuntu-latest
    if: ${{ failure() }}

    env:
      FORCE_COLOR: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup git
        run: |
          git config --global user.email "services@iprojects.ru"
          git config --global user.name "sendsay-cat"

      - name: Setup ssh-key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SENDSAY_CAT_KEY }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
  
      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Autofix
        run: yarn lint:fix

      - name: Commit
        run: |
          git add .
          git commit -m "autofix"
          git push origin
